# Generated by Django 5.2.7 on 2025-10-17 13:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "material_category",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pickup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer", models.CharField(blank=True, max_length=200, null=True)),
                ("location", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "date_collected",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("waste_type", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "collected_by",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vendor_name",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "vendor_type",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "date_received",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "delivered_by",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "vendor_location",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("business", "Business"),
                            ("collector", "Collector"),
                            ("upcycler", "Upcycler"),
                        ],
                        default="business",
                        max_length=300,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
