# Generated by Django 5.2.7 on 2025-10-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_delete_pickup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("business", "Business"),
                    ("collector", "Collector"),
                    ("household", "Household"),
                ],
                default="business",
                max_length=300,
            ),
        ),
    ]
