# Generated by Django 5.2.7 on 2025-10-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profile_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_type",
            field=models.CharField(
                choices=[("business", "Business"), ("household", "Household")],
                max_length=300,
            ),
        ),
    ]
