# Generated by Django 5.2.7 on 2025-10-31 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_profile_user_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Material",
        ),
        migrations.DeleteModel(
            name="Vendor",
        ),
    ]
