# Generated by Django 5.2.7 on 2025-11-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_delete_material_delete_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("business", "Business"),
                    ("household", "Household"),
                    ("recycler", "Recycler"),
                ],
                max_length=300,
            ),
        ),
    ]
