# Generated by Django 5.2.7 on 2025-10-22 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0005_pickups_collected_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="WasteAnalyticsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("co2_saved", models.PositiveIntegerField(default=0)),
                (
                    "pickup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer",
                        to="clients.pickupplan",
                    ),
                ),
            ],
        ),
    ]
