# Generated by Django 5.2.7 on 2025-10-23 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        ("clients", "0005_pickups_collected_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wasteanalyticsdata",
            name="pickup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.pickups",
            ),
        ),
    ]
