# Generated by Django 5.2.7 on 2025-11-21 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_alter_wasteanalyticsdata_pickup"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WasteAnalyticsData",
        ),
    ]
