# Generated by Django 5.2.7 on 2025-10-17 13:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickups_per_month", models.PositiveIntegerField()),
                ("pickups_done", models.PositiveIntegerField(default=0)),
                ("locations", models.PositiveIntegerField(default=1)),
                ("is_popular", models.BooleanField(default=False)),
                ("name", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=2000, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=250, null=True),
                ),
                ("address", models.TextField()),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "material_type",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "date_requested",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "selected_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clients.plans",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PickupPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("pickups_done", models.PositiveIntegerField(default=0)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.client",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.plans",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pickups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("completed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "pickup_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.pickupplan",
                    ),
                ),
            ],
        ),
    ]
