# Generated by Django 5.2.7 on 2025-10-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickups",
            name="pickup_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
