# Generated by Django 5.2.7 on 2025-10-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_pickups_pickup_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickups",
            name="waste_type",
            field=models.CharField(blank=True, null=True),
        ),
    ]
