# Generated by Django 5.2.7 on 2025-10-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_pickups_waste_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plans",
            name="locations",
        ),
        migrations.AddField(
            model_name="pickups",
            name="images",
            field=models.ImageField(blank=True, null=True, upload_to="pickup_images/"),
        ),
        migrations.AddField(
            model_name="pickups",
            name="weight",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plans",
            name="all_locations",
            field=models.BooleanField(default=True),
        ),
    ]
