# Generated by Django 5.2.7 on 2025-10-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "clients",
            "0004_remove_plans_locations_pickups_images_pickups_weight_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pickups",
            name="collected_by",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
