# Generated by Django 5.2.7 on 2025-10-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_pickups_collected_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pickups",
            name="waste_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("plastic", "Plastic"),
                    ("paper_cardboard", "Paper & Cardboard"),
                    ("glass", "Glass"),
                    ("metal", "Metal"),
                    ("organic", "Organic / Food Waste"),
                    ("e_waste", "E-Waste"),
                    ("textiles", "Textiles / Fabric"),
                    ("hazardous", "Hazardous Waste"),
                    ("medical", "Medical Waste"),
                    ("construction", "Construction / Rubble"),
                    ("mixed", "Mixed Waste"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
