# Generated by Django 5.2.7 on 2025-11-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_alter_pickups_waste_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pickups",
            name="completed",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("pending", "Pending"),
                    ("cancelled", " Cancelled"),
                ],
                default="pending",
                max_length=300,
            ),
        ),
    ]
