# Generated by Django 5.2.7 on 2025-11-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0007_alter_pickups_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickups",
            name="waste_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("small", "Small/Light/Equivalent to wheelie (R999)"),
                    (
                        "medium",
                        "Medium/Standard/Equivalent to half bakkie load (R1599)",
                    ),
                    ("large", "Large/Bulky items/Full bakkie size and beyond (R2999)"),
                ],
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pickups",
            name="waste_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("plastic", "Plastic"),
                    ("paper_cardboard", "Paper & Cardboard"),
                    ("glass", "Glass"),
                    ("metal", "Metal"),
                    ("organic/food/garden", "Organic /Garden/ Food Waste"),
                    ("e_waste", "E-Waste"),
                    ("textiles/clothing", "Textiles /Clothing /Fabric"),
                    ("medical", "Medical Waste"),
                    ("construction", "Construction / Rubble"),
                    ("mixed", "Mixed Waste"),
                    ("furniture/appliances", "Furniture / Appliances"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
