# Generated by Django 5.2.7 on 2025-11-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0008_pickups_waste_size_alter_pickups_waste_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pickups",
            name="waste_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("small", "Small/Light/Equivalent to wheelie (R1499)"),
                    (
                        "medium",
                        "Medium/Standard/Equivalent to half bakkie load (R1999)",
                    ),
                    ("large", "Large/Bulky items/Full bakkie size and beyond (R3499)"),
                ],
                max_length=300,
                null=True,
            ),
        ),
    ]
