# Generated by Django 5.2.7 on 2025-11-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0009_alter_pickups_waste_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plans",
            name="all_locations",
            field=models.BooleanField(default=False),
        ),
    ]
