# Generated by Django 5.2.7 on 2025-10-24 11:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerPlans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_pickups_per_month", models.PositiveIntegerField()),
                ("customer_pickups_done", models.PositiveIntegerField(default=0)),
                ("customer_all_locations", models.BooleanField(default=True)),
                ("customerplan_is_popular", models.BooleanField(default=False)),
                ("plan_name", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "plan_price",
                    models.DecimalField(decimal_places=2, default=2000, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "customer_email",
                    models.EmailField(blank=True, max_length=250, null=True),
                ),
                ("customer_address", models.TextField()),
                (
                    "customer_phone_number",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "customer_material_type",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "customer_date_requested",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="household.customerplans",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerPickups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_scheduled_date", models.DateField()),
                ("customer_pickup_time", models.TimeField(blank=True, null=True)),
                ("customer_pickup_completed", models.BooleanField(default=False)),
                ("customer_notes", models.TextField(blank=True, null=True)),
                ("customer_waste_type", models.CharField(blank=True, null=True)),
                (
                    "customer_images",
                    models.ImageField(
                        blank=True, null=True, upload_to="pickup_images/"
                    ),
                ),
                ("customer_weight", models.PositiveIntegerField(default=0)),
                (
                    "customer_collected_by",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "customer_pickup_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="household.customerplans",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerPickupPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("household_month", models.DateField()),
                ("household_pickups_done", models.PositiveIntegerField(default=0)),
                (
                    "household_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="household.customer",
                    ),
                ),
                (
                    "household_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="household.customerplans",
                    ),
                ),
            ],
        ),
    ]
