# Generated by Django 5.2.7 on 2025-10-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="customer_name",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
