# Generated by Django 5.2.7 on 2025-11-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0003_alter_customerpickups_customer_waste_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerpickups",
            name="customer_pickup_completed",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("pending", "Pending"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=300,
            ),
        ),
    ]
