# Generated by Django 5.2.7 on 2025-11-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0004_alter_customerpickups_customer_pickup_completed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerpickups",
            name="customer_weight",
        ),
        migrations.RemoveField(
            model_name="customerplans",
            name="customer_all_locations",
        ),
        migrations.AddField(
            model_name="customerpickups",
            name="waste_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("small", "Small/Light/Equivalent to plastic bag (R99)"),
                    ("medium", "Medium/Standard/Equivalent to bin bag (R149)"),
                    ("large", "Large/Bulky items (R399)"),
                ],
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customerplans",
            name="once_off_service",
            field=models.BooleanField(default=False),
        ),
    ]
