# Generated by Django 5.2.7 on 2025-11-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0005_remove_customerpickups_customer_weight_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerpickups",
            name="waste_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("small", "Small/Light/Equivalent to plastic bag (R499)"),
                    ("medium", "Medium/Standard/Equivalent to bin bag (R799)"),
                    ("large", "Large/Bulky items (R1999)"),
                ],
                max_length=300,
                null=True,
            ),
        ),
    ]
