# Generated by Django 5.2.7 on 2025-11-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0006_alter_customerpickups_waste_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerpickups",
            name="waste_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("small", "Small/Light/Equivalent to plastic bag (R499)"),
                    ("medium", "Medium/Standard/Equivalent to bin bag (R899)"),
                    ("large", "Large/Bulky items (R1999)"),
                ],
                max_length=300,
                null=True,
            ),
        ),
    ]
