# Generated by Django 5.2.7 on 2025-11-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0007_alter_customerpickups_waste_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerpickups",
            name="customer_waste_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("plastic", "Plastic"),
                    ("paper_cardboard", "Paper & Cardboard"),
                    ("glass", "Glass"),
                    ("metal", "Metal"),
                    ("organic/food/garden", "Organic /Garden/ Food Waste"),
                    ("e_waste", "E-Waste"),
                    ("textiles/clothing", "Textiles /Clothing /Fabric"),
                    ("medical", "Medical Waste"),
                    ("construction", "Construction / Rubble"),
                    ("mixed", "Mixed Waste"),
                    ("furniture/appliances", "Furniture / Appliances"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
