# Generated by Django 5.2.7 on 2025-11-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0008_alter_customerpickups_customer_waste_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerpickups",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerpickups",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
