# Generated by Django 5.2.7 on 2025-11-28 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0010_alter_customerpickups_waste_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="customerpickups",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="customerpickups",
            name="longitude",
        ),
    ]
