# Generated by Django 5.2.7 on 2025-11-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "household",
            "0011_remove_customer_latitude_remove_customer_longitude_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="customer_address",
        ),
        migrations.AddField(
            model_name="customerpickups",
            name="customer_address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
