# Generated by Django 5.2.7 on 2025-12-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0012_remove_customer_customer_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerpickups",
            name="waste_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("small", "Small/Light/Equivalent to plastic bag (R799)"),
                    ("medium", "Medium/Standard/Equivalent to bin bag (R1499)"),
                    ("large", "Large/Bulky items (R2499)"),
                ],
                max_length=300,
                null=True,
            ),
        ),
    ]
